### ISSUE TITLE
Date/DateTime fields lead to exception

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerBAP/orientdb-oda-birt#1]
Exception in eclipse:

```java
com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content for record: "result":[{"@type":"d","@rid":"#-2:0","@version":0,"fact":0.0,"plan":0.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u041b\u041e\u0414-\u0421\u043c\u043e\u043b\u0435\u043d\u0441\u043a-2015","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:1","@version":0,"fact":0.0,"plan":0.0,"forecast":0.0,"financialMonth":"2017-02-01 00:00:00","project":"\u0421\u0435\u0440\u0422\u0435\u0441\u0442","sector":"\u0414\u0435\u043f\u0430\u0440\u0442\u0430\u043c\u0435\u043d\u0442 \u043a\u043e\u043c\u043f\u043b\u0435\u043a\u0441\u043d\u044b\u0445 \u043f\u0440\u043e\u0435\u043a\u0442\u043e\u0432","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:2","@version":0,"fact":-39000.0,"plan":0.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u0421\u0435\u0440_\u043f\u0440\u043e\u0447\u0438\u0435 \u0440\u0430\u0441\u0445\u043e\u0434\u044b \u0414\u041a\u041f","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:3","@version":0,"fact":-195.0,"plan":0.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u0422\u0435\u0441\u0442 3","sector":"\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u043e\u043d\u043d\u0430\u044f \u0431\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0441\u0442\u044c","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:4","@version":0,"fact":-195.0,"plan":-260.0,"forecast":0.0,"financialMonth":"2017-02-01 00:00:00","project":"\u0422\u0435\u0441\u0442 3","sector":"\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u043e\u043d\u043d\u0430\u044f \u0431\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0441\u0442\u044c","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:5","@version":0,"fact":0.0,"plan":0.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u041c\u0424\u0426-\u0421\u043c\u043e\u043b\u0435\u043d\u0441\u043a-2015","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:6","@version":0,"fact":0.0,"plan":-260.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u0422\u0435\u0441\u0442 2","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:7","@version":0,"fact":0.0,"plan":0.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u0421\u0435\u0440\u0422\u0435\u0441\u0442","sector":"\u0414\u0435\u043f\u0430\u0440\u0442\u0430\u043c\u0435\u043d\u0442 \u043a\u043e\u043c\u043f\u043b\u0435\u043a\u0441\u043d\u044b\u0445 \u043f\u0440\u043e\u0435\u043a\u0442\u043e\u0432","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:8","@version":0,"fact":-209800.5,"plan":0.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u041c\u0424\u0426-\u041c\u042d\u0420-\u041c\u0414\u041c-2015","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:9","@version":0,"fact":-195.0,"plan":-260.0,"forecast":0.0,"financialMonth":"2017-02-01 00:00:00","project":"\u0422\u0435\u0441\u0442 2","sector":"\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u043e\u0435 \u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u043e","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:10","@version":0,"fact":-195.0,"plan":0.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u0422\u0435\u0441\u0442 2","sector":"\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u043e\u0435 \u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u043e","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:11","@version":0,"fact":-130000.0,"plan":-780000.0,"forecast":0.0,"financialMonth":"2017-03-01 00:00:00","project":"\u041b\u041e\u0414-\u0421\u043c\u043e\u043b\u0435\u043d\u0441\u043a-2015","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:12","@version":0,"fact":0.0,"plan":0.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u0420\u0435\u0435\u0441\u0442\u0440\u044b-\u041c\u041e-\u041c\u0438\u043d\u0433\u043e\u0441-2015","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:13","@version":0,"fact":0.0,"plan":-260.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u0422\u0435\u0441\u0442 3","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:14","@version":0,"fact":-195.0,"plan":-260.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u0422\u0435\u0441\u0442 1","sector":"\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u043e\u0435 \u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u043e","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:15","@version":0,"fact":0.0,"plan":0.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u041c\u0424\u0426-\u0415\u0410\u041e-2015","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:16","@version":0,"fact":-195.0,"plan":-260.0,"forecast":0.0,"financialMonth":"2017-02-01 00:00:00","project":"\u0422\u0435\u0441\u0442 1","sector":"\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u043e\u0435 \u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u043e","reportItem":"\u0421\u0443\u0431\u043f\u043e\u0434\u0440\u044f\u0434\u044b \u0441 \u043a\u043e\u043d\u0442\u0438\u043d\u0434\u0436\u0435\u043d\u0441\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:17","@version":0,"fact":-15153.5,"plan":0.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u041b\u041e\u0414-\u0421\u043c\u043e\u043b\u0435\u043d\u0441\u043a-2015","reportItem":"\u041a\u043e\u043c\u0430\u043d\u0434\u0438\u0440\u043e\u0432\u043a\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:18","@version":0,"fact":-30.0,"plan":-50.0,"forecast":0.0,"financialMonth":"2017-02-01 00:00:00","project":"\u0421\u0435\u0440\u0422\u0435\u0441\u0442","sector":"\u0414\u0435\u043f\u0430\u0440\u0442\u0430\u043c\u0435\u043d\u0442 \u043a\u043e\u043c\u043f\u043b\u0435\u043a\u0441\u043d\u044b\u0445 \u043f\u0440\u043e\u0435\u043a\u0442\u043e\u0432","reportItem":"\u041a\u043e\u043c\u0430\u043d\u0434\u0438\u0440\u043e\u0432\u043a\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}, {"@type":"d","@rid":"#-2:19","@version":0,"fact":-17708.75,"plan":0.0,"forecast":0.0,"financialMonth":"2017-01-01 00:00:00","project":"\u0421\u0435\u0440_\u043f\u0440\u043e\u0447\u0438\u0435 \u0440\u0430\u0441\u0445\u043e\u0434\u044b \u0414\u041a\u041f","reportItem":"\u041a\u043e\u043c\u0430\u043d\u0434\u0438\u0440\u043e\u0432\u043a\u0438","@fieldTypes":"fact=d,plan=d,forecast=d,financialMonth=t"}]
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.fromString(ORecordSerializerJSON.java:323)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.fromString(ORecordSerializerJSON.java:171)
	at com.orientechnologies.orient.core.record.ORecordAbstract.fromJSON(ORecordAbstract.java:170)
	at com.orientechnologies.orient.core.record.impl.ODocument.fromJSON(ODocument.java:1751)
	at org.orienteer.birt.orientdb.impl.HttpQuery.prepare(HttpQuery.java:75)
	at org.orienteer.birt.orientdb.ui.impl.CustomDataSetWizardPage.updateDesign(CustomDataSetWizardPage.java:279)
	at org.orienteer.birt.orientdb.ui.impl.CustomDataSetWizardPage.savePage(CustomDataSetWizardPage.java:254)
	at org.orienteer.birt.orientdb.ui.impl.CustomDataSetWizardPage.collectDataSetDesign(CustomDataSetWizardPage.java:168)
	at org.eclipse.datatools.connectivity.oda.design.internal.ui.DataSetWizardPageCore.finishDataSetDesign(DataSetWizardPageCore.java:395)
	at org.eclipse.datatools.connectivity.oda.design.internal.ui.DataSetWizardBase.collectDataSetDesignFromPage(DataSetWizardBase.java:365)
	at org.eclipse.datatools.connectivity.oda.design.internal.ui.DataSetWizardBase.finishDataSetDesign(DataSetWizardBase.java:387)
	at org.eclipse.datatools.connectivity.oda.design.internal.ui.DataSetWizardBase.performFinish(DataSetWizardBase.java:99)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:790)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:423)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
```

**Comment by SergeyAsm** [comment]
fix in https://github.com/OrienteerBAP/orientdb-oda-birt/commit/303dffc07b5a2b91d9ebc21240d24b29d33fa2af
