### ISSUE TITLE
Failing if query return nothing

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerBAP/orientdb-oda-birt#3]
```java
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.orienteer.birt.orientdb.impl.HttpQuery.prepare(HttpQuery.java:84)
	at org.orienteer.birt.orientdb.ui.impl.CustomDataSetWizardPage.updateDesign(CustomDataSetWizardPage.java:279)
	at org.orienteer.birt.orientdb.ui.impl.CustomDataSetWizardPage.savePage(CustomDataSetWizardPage.java:254)
	at org.orienteer.birt.orientdb.ui.impl.CustomDataSetWizardPage.collectDataSetDesign(CustomDataSetWizardPage.java:168)
	at org.eclipse.datatools.connectivity.oda.design.internal.ui.DataSetWizardPageCore.finishDataSetDesign(DataSetWizardPageCore.java:395)
	at org.eclipse.datatools.connectivity.oda.design.internal.ui.DataSetWizardBase.collectDataSetDesignFromPage(DataSetWizardBase.java:365)
	at org.eclipse.datatools.connectivity.oda.design.internal.ui.DataSetWizardBase.finishDataSetDesign(DataSetWizardBase.java:387)
	at org.eclipse.datatools.connectivity.oda.design.internal.ui.DataSetWizardBase.performFinish(DataSetWizardBase.java:99)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:790)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:423)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5219)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4553)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4143)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
```

**Comment by SergeyAsm** [comment]
fix in https://github.com/OrienteerBAP/orientdb-oda-birt/commit/0a87832a951ee2cf35ec281ccad2331e6b3ba979
